apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  php-app-env: {{ .Values.php.appEnv | quote }}
  php-app-debug: {{ .Values.php.appDebug | quote }}
  php-cors-allow-origin: {{ .Values.php.corsAllowOrigin | quote }}
  php-trusted-hosts: ^{{ join "|" .Values.php.trustedHostRegexps }}$
  php-trusted-proxies: "{{ join "," .Values.php.trustedProxies }}"
  auth-header-roles: x-token-user-roles
  auth-header-email: x-token-user-email
  mercure-url: "http://{{ include "common.names.fullname" . }}/.well-known/mercure"
  mercure-public-url: {{ .Values.mercure.publicUrl | default "http://127.0.0.1/.well-known/mercure" | quote }}
  Caddyfile: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.caddy.configBlock "context" $ ) | nindent 4 }}
