apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-caddy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  Caddyfile: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.caddy.configBlock "context" $ ) | nindent 4 }}
