---
apiVersion: v1
kind: Secret
metadata:
  name: my-existing-secret
  namespace: default
type: Opaque
data:
  # postgresql://app:appPassword@asset-repository-postgresql/api?serverVersion=13&charset=utf8
  database-url: |
    cG9zdGdyZXNxbDovL2FwcDphcHBQYXNzd29yZEBhc3NldC1yZXBvc2l0b3J5LXBvc3RncmVzcWwv
    YXBpP3NlcnZlclZlcnNpb249MTMmY2hhcnNldD11dGY4Cg==
  postgres-password: "cG9zdGdyZXMtcm9vdC1wYXNzd29yZAo="  # postgres-root-password
  password: "YXBwUGFzc3dvcmQK" # appPassword
  php-app-secret: "YXBwLXNlY3JldAo=" # app-secret
  mercure-jwt-secret: "bWVyY3VyZS1qd3Qtc2VjcmV0Cg==" # mercure-jwt-secret
