---
apiVersion: v1
kind: Secret
metadata:
  name: my-existing-secret
  namespace: default
type: Opaque
data:
  # postgresql://app:appPassword@asset-repository-postgresql/api?serverVersion=13&charset=utf8
  database-url: |
    cG9zdGdyZXNxbDovL2FwcDphcHBQYXNzd29yZEBhc3NldC1yZXBvc2l0b3J5LXBvc3RncmVzcWwv
    YXBpP3NlcnZlclZlcnNpb249MTMmY2hhcnNldD11dGY4Cg==
  postgres-password: "cG9zdGdyZXMtcm9vdC1wYXNzd29yZAo="  # postgres-root-password
  password: "YXBwUGFzc3dvcmQK" # appPassword
  php-app-secret: "YXBwLXNlY3JldAo=" # app-secret
  mercure-jwt-secret: "bWVyY3VyZS1qd3Qtc2VjcmV0Cg==" # mercure-jwt-secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-nginx-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app-nginx-1
  template:
    metadata:
      labels:
        app: test-app-nginx-1
        asset-repository/export: kube-exporter
      annotations:
        asset-repository/container-instances: nginx
        asset-repository/asset.identifier: front
        asset-repository/version: "1.0"
    spec:
      containers:
      - image: nginx:stable-alpine3.17-slim
        name: nginx
        ports:
        - containerPort: 80
          name: http
