apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: asset-repository
build:
  artifacts:
    - image: asset-repository-php
      context: ../asset-repository/api
      docker:
        target: app_php
    - image: asset-repository-caddy
      context: ../asset-repository/api
      docker:
        target: app_caddy
    - image: asset-repository-kube-exporter
      context: ../asset-repository-kube-exporter
    - image: asset-repository-file-exporter
      context: ../asset-repository-file-exporter

deploy:
  kubeContext: minikube
  helm:
    releases:
    - name: asset-repository
      chartPath: helm/asset-repository
      namespace: default
      setValueTemplates:
        php.image.repository: "{{.IMAGE_REPO_asset_repository_php}}"
        php.image.tag: "{{.IMAGE_TAG_asset_repository_php}}@{{.IMAGE_DIGEST_asset_repository_php}}"
        caddy.image.repository: "{{.IMAGE_REPO_asset_repository_caddy}}"
        caddy.image.tag: "{{.IMAGE_TAG_asset_repository_caddy}}@{{.IMAGE_DIGEST_asset_repository_caddy}}"
      valuesFiles:
        - skaffold-values.yaml
    - name: asset-repository-kube-exporter
      chartPath: helm/asset-repository-kube-exporter
      namespace: default
      setValueTemplates:
        image.repository: "{{.IMAGE_REPO_asset_repository_kube_exporter}}"
        image.tag: "{{.IMAGE_TAG_asset_repository_kube_exporter}}@{{.IMAGE_DIGEST_asset_repository_kube_exporter}}"
      valuesFiles:
        - skaffold-values-kube-exporter.yaml
    - name: asset-repository-file-exporter
      chartPath: helm/asset-repository-file-exporter
      namespace: default
      setValueTemplates:
        image.repository: "{{.IMAGE_REPO_asset_repository_file_exporter}}"
        image.tag: "{{.IMAGE_TAG_asset_repository_file_exporter}}@{{.IMAGE_DIGEST_asset_repository_file_exporter}}"
      valuesFiles:
        - skaffold-values-file-exporter.yaml
    hooks:
      before:
        - host:
            command: [ "kubectl", "--context=minikube", "apply", "-f", "skaffold-extra-manifests.yaml" ]
