{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
data:
  {{- toYaml .Values.configmap.data | nindent 2 }}
{{- end }}
